### PR TITLE
Native functions invocation

### PR DESCRIPTION
**Pull request by PabloKowalczyk**
This PR adds PHPCSFixer with `native_function_invocation` which can improve performance a little bit - `Add leading \ before function invocation to speed up resolving.`.

### CODE REVIEW

**Comment by neomerx** [comment]
I've done tests on PHP 7.3 and it improves performance on average for 1,6% (2,3% for small data sets and 1,0% for bigger ones) which is good thank to you :wink: 

We should go with it, but, o boy, the fixer messy as hell :smiling_imp: Instead of [just importing a function](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2739) it changes every single usage of it. Import currently is not supported and even if imported manually the fixer does not understand it. So adding some mess for 1,6% is the only option :smile: 

I'm OK to merge it, however, a couple of tweaks needed
- single commit with a comment 'Close #228'
- Turn off cache for cs (add `->setUsingCache(false)` to `.php_cs.dist`, remove `.php_cs.dist` from `.gitignore`)
- scripts in `composer.json` should be unified as
```
  "scripts": {
    "test": ["@test-unit", "@test-cs", "@test-md", "@test-cs-fixer"],
    "test-unit": "./vendor/phpunit/phpunit/phpunit --coverage-text",
    "test-unit-phpdbg": "phpdbg -qrr ./vendor/bin/phpunit --coverage-text",
    "test-cs": "./vendor/bin/phpcs -p -s --standard=PSR2 ./src ./tests",
    "test-md": "./vendor/bin/phpmd ./src text codesize,controversial,cleancode,design,unusedcode,naming",
    "test-cs-fixer": "./vendor/bin/php-cs-fixer fix --diff --dry-run -v",
    "cs-fixer": "./vendor/bin/php-cs-fixer fix --diff -v --ansi"
  }
```
- `.php_cs.dist` should be added to `.gitattributes`
- can you please add calls `test-cs`, `test-md` to `.travis.yml`?

**Comment by neomerx** [comment]
And one more. PR to `develop`.

**Comment by PabloKowalczyk** [comment]
Why `Turn off cache for cs`?

**Comment by PabloKowalczyk** [comment]
"remove `.php_cs.dist` from `.gitignore`" - did you mean `.php_cs.cache`?

**Comment by PabloKowalczyk** [comment]
A small tip: "single commit with a comment 'Close #228'" when you merging PR you can select "squash and merge" and then pass commit name :)

**Comment by neomerx** [comment]
Thanks for the changes and the tip. I believe if I squash someone's changes I become an author of them which is unfair to authors.

**Comment by Ilyes512** [comment]
Would it not have been te same and look nicer to instead do something like:


```php
use function is_iterable;
```

Not tested it, but I would not be surprised if it would benefit from the same speed improvements.

**Comment by neomerx** [comment]
@Ilyes512 I cite myself from a message above
> We should go with it, but, o boy, the fixer messy as hell  Instead of [just importing a function](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2739) it changes every single usage of it. Import currently is not supported and even if imported manually the fixer does not understand it.

**Pull request merged**
