### PR TITLE
Add failing test case to illustrate #98

### PR DESCRIPTION
**Pull request by hglattergotz**
Add a failing test case to better explain the issue in #98

### CODE REVIEW

**Comment by neomerx** [comment]
It should fail, right?

**Comment by hglattergotz** [comment]
Yes, this test fails on purpose to demonstrate the problem.

**Comment by neomerx** [comment]
if the following line is added to fieldset filter the test will pass

``` php
     'sites' => [Site::LINK_POSTS, Site::ATTRIBUTE_NAME],
```

So basically it's about filter logic

**Comment by neomerx** [comment]
I've updated the test

**Pull request merged**
