### PR TITLE
Feature/issue36

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by neomerx** [comment]
@sumeko is it a duplicate of code in `feature/issue36`?

**Comment by neomerx** [comment]
duplicates #36 

I'll add more test coverage to `feature/issue36` branch and then merge

**Comment by nueko** [comment]
I am sorry, that was accidentally click :sleepy:

**Comment by neomerx** [comment]
no probs. Check my other messages.

I've made phalcon env and you project works! :smile: 

Check my PR out. It adds composer support.

Next 2 big steps:
- tests, license, other small issues
- migrate `the trait`

**Pull request closed without merging**
